[build]
  publish = "."

[[redirects]]
  from = "/api/finnhub/*"
  to = "/.netlify/functions/finnhub/:splat"
  status = 200

[[redirects]]
  from = "/api/proxy"
  to = "/.netlify/functions/proxy"
  status = 200
